-- =============================================================
-- Connective Health Global - Seed Data
-- ~50 seed listings across research, supplements, providers
-- =============================================================

-- Helper function to get category ids
-- Categories: 1=ME/CFS, 2=Long COVID, 3=POTS, 4=Fibromyalgia,
--             5=MCAS, 6=EDS/HSD, 7=Autoimmune, 8=Lyme, 9=General

-- Tier: 1=CLINICAL_TRIAL, 2=MULTIPLE_STUDIES, 3=PATIENT_REPORTS,
--       4=EMERGING, 5=LISTING_ONLY
-- Type: 1=Research, 2=Treatment, 3=Supplement, 4=Clinic, 5=Provider,
--       6=Support Service, 7=Clinical Trial, 8=Article

-- === SUPPLEMENTS (Tier 1-2, can carry affiliate links) ===
insert into public.listings (content_type_id, title, slug, description, summary, evidence_tier_id, evidence_notes, affiliate_network, is_published, categories) values
(3, 'Coenzyme Q10 (CoQ10)', 'coq10', 'Coenzyme Q10 is a vitamin-like compound involved in cellular energy production. Studies show benefit in ME/CFS and fibromyalgia for reducing fatigue and improving mitochondrial function.', 'Antioxidant supporting mitochondrial function and energy production', 2, 'Multiple studies show reduced fatigue in ME/CFS patients; Cochrane review ongoing', 'iHerb', true, '{1,4,9}'),
(3, 'NADH', 'nadh', 'Nicotinamide adenine dinucleotide (NADH) plays a crucial role in cellular energy metabolism. Clinical trials suggest benefits for fatigue reduction in chronic conditions.', 'Cellular energy cofactor studied for fatigue reduction', 2, 'Placebo-controlled trials show reduced fatigue in ME/CFS; multiple studies', 'iHerb', true, '{1,2,4}'),
(3, 'D-Ribose', 'd-ribose', 'A naturally occurring sugar that supports ATP production. Clinical studies demonstrate improved energy levels and reduced pain in fibromyalgia and ME/CFS patients.', 'ATP-supporting sugar shown to improve energy in clinical studies', 2, 'Two independent studies show energy improvement in fibromyalgia and ME/CFS', 'iHerb', true, '{1,4,9}'),
(3, 'Low-Dose Naltrexone (LDN)', 'low-dose-naltrexone', 'LDN is an off-label use of naltrexone at low doses (1-4.5mg) that modulates immune function. Growing evidence supports use in autoimmune conditions, ME/CFS, and fibromyalgia.', 'Immune-modulating therapy at low doses for chronic conditions', 2, 'Multiple open-label and retrospective studies; RCTs ongoing for ME/CFS and fibromyalgia', 'iHerb', true, '{1,4,5,7}'),
(3, 'Magnesium Glycinate', 'magnesium-glycinate', 'Highly bioavailable form of magnesium essential for muscle function, sleep quality, and nervous system regulation. Particularly relevant for POTS and fibromyalgia.', 'High-absorption magnesium for muscle and nerve function', 2, 'Multiple studies support magnesium deficiency in chronic conditions; improved sleep and muscle function demonstrated', 'iHerb', true, '{3,4,6,9}'),
(3, 'Vitamin B12 (Methylcobalamin)', 'vitamin-b12-methylcobalamin', 'Active form of B12 essential for neurological function, energy metabolism, and red blood cell formation. Sublingual or injectable forms used in chronic fatigue.', 'Active B12 for neurological and energy support', 2, 'Multiple studies show B12 deficiency common in ME/CFS; supplementation improves energy in deficient patients', 'iHerb', true, '{1,2,4}'),
(3, 'Omega-3 Fatty Acids (Fish Oil)', 'omega-3', 'Essential fatty acids with potent anti-inflammatory properties. Clinical evidence supports benefits for autoimmune conditions, cardiovascular health, and cognitive function.', 'Anti-inflammatory essential fatty acids', 1, 'Multiple RCTs demonstrate anti-inflammatory benefits; supported by systematic reviews for autoimmune conditions', 'iHerb', true, '{4,5,7,9}'),
(3, 'Vitamin D3', 'vitamin-d3', 'Essential vitamin with immunomodulatory properties. Deficiency is common in autoimmune conditions and chronic illness. Supplementation supports immune function and bone health.', 'Immune-supporting vitamin for chronic illness', 1, 'Extensive RCT evidence for immune function; meta-analyses show benefits for autoimmune conditions', 'iHerb', true, '{5,7,8,9}'),
(3, 'Curcumin (Turmeric)', 'curcumin', 'Potent anti-inflammatory compound from turmeric. Clinical evidence supports benefits for pain reduction in osteoarthritis and fibromyalgia.', 'Anti-inflammatory compound from turmeric', 1, 'Multiple RCTs demonstrate anti-inflammatory effects; systematic reviews support pain reduction', 'iHerb', true, '{4,7,5}'),
(3, 'Melatonin', 'melatonin', 'Key sleep hormone with additional immunomodulatory and antioxidant properties. Studies show benefits for sleep quality in chronic conditions and potential benefits for Long COVID.', 'Sleep hormone with immune-modulating properties', 2, 'Multiple studies support sleep improvement; emerging evidence for Long COVID symptom management', 'iHerb', true, '{1,2,3,9}'),
(3, 'L-Carnitine', 'l-carnitine', 'Amino acid derivative essential for fatty acid transport into mitochondria. Clinical trials show reduced fatigue and improved cognitive function in ME/CFS.', 'Mitochondrial support for energy and cognition', 2, 'RCTs show reduced fatigue and improved cognitive function in ME/CFS patients', 'iHerb', true, '{1,2,4}'),
(3, 'Probiotics (Multi-Strain)', 'probiotics', 'Beneficial bacteria that support gut health, which is commonly disrupted in chronic illness. Evidence supports role in immune modulation and symptom management.', 'Gut health support for immune and digestive health', 2, 'Multiple studies show gut microbiome alterations in chronic conditions; probiotics improve digestive and immune symptoms', 'iHerb', true, '{1,2,5,9}'),
(3, 'Quercetin', 'quercetin', 'Plant flavonoid with mast cell stabilising and anti-inflammatory properties. Particularly relevant for MCAS, allergies, and Long COVID.', 'Mast cell stabiliser and anti-inflammatory flavonoid', 2, 'Multiple studies support mast cell stabilisation; emerging evidence for Long COVID and MCAS management', 'iHerb', true, '{2,3,5,9}'),
(3, 'N-Acetyl Cysteine (NAC)', 'nac', 'Precursor to glutathione, the bodys master antioxidant. Supports detoxification, respiratory health, and immune function. Studied in chronic conditions for oxidative stress reduction.', 'Glutathione precursor for antioxidant support', 2, 'Multiple studies support glutathione depletion in chronic illness; NAC shown to reduce oxidative stress markers', iHerb, true, '{1,2,5,8}'),
(3, 'Ashwagandha', 'ashwagandha', 'Adaptogenic herb studied for stress reduction, adrenal support, and energy. Clinical trials show reduced cortisol and improved quality of life in chronic stress conditions.', 'Adaptogenic herb for stress and adrenal support', 2, 'Multiple RCTs demonstrate cortisol reduction and improved wellbeing in stressed populations', iHerb, true, '{1,4,9}');

-- === RESEARCH STUDIES ===
insert into public.listings (content_type_id, title, slug, description, summary, evidence_tier_id, external_url, is_published, categories, tags) values
(1, 'PACE Trial: Exercise and Pacing for ME/CFS', 'pace-trial-2011', 'The PACE trial was a large randomised controlled trial evaluating cognitive behavioural therapy (CBT) and graded exercise therapy (GET) for ME/CFS. Highly controversial with significant methodological criticism from patient advocacy groups.', 'Large RCT of CBT and GET for ME/CFS - highly controversial', 1, 'https://doi.org/10.1016/S0140-6736(11)60096-2', true, '{1}', '{"controversial","RCT","exercise","CBT"}'),
(1, 'Rituximab for ME/CFS: Phase II Trial', 'rituximab-mecfs-2017', 'Phase II randomised controlled trial of rituximab (B-cell depletion therapy) for ME/CFS. Initial promising results were not confirmed in later Phase III trials.', 'Rituximab RCT for ME/CFS - Phase II', 1, 'https://doi.org/10.1371/journal.pone.0177810', true, '{1}', '{"rituximab","RCT","B-cell","autoimmune"}'),
(1, 'Long COVID: Nature Reviews Synthesis', 'long-covid-nature-2023', 'Comprehensive synthesis of Long COVID pathophysiology, epidemiology, and clinical management published in Nature Reviews. Covers autonomic dysfunction, immune dysregulation, and treatment approaches.', 'Nature Reviews synthesis of Long COVID evidence', 1, 'https://doi.org/10.1038/s41579-022-00846-2', true, '{2}', '{"COVID-19","PASC","review","pathophysiology"}'),
(1, 'POTS: Pathophysiology and Management (Heart Rhythm Society)', 'pots-consensus-2022', 'Expert consensus statement on the diagnosis and management of Postural Orthostatic Tachycardia Syndrome. Covers pharmacological and non-pharmacological treatment approaches.', 'Heart Rhythm Society consensus on POTS', 2, 'https://doi.org/10.1016/j.hrthm.2022.07.009', true, '{3}', '{"POTS","consensus","guidelines","management"}'),
(1, 'Fibromyalgia: Evolving Concepts and Treatment (Lancet)', 'fibromyalgia-lancet-2021', 'Lancet Seminar reviewing current understanding of fibromyalgia pathophysiology, diagnosis, and evidence-based treatment approaches.', 'Lancet review of fibromyalgia evidence', 1, 'https://doi.org/10.1016/S0140-6736(21)01388-0', true, '{4}', '{"fibromyalgia","review","treatment","Lancet"}'),
(1, 'MCAS: Diagnostic Criteria and Treatment Consensus', 'mcas-consensus-2019', 'International consensus on diagnostic criteria and treatment approaches for Mast Cell Activation Syndrome.', 'International consensus on MCAS diagnosis and treatment', 2, 'https://doi.org/10.1007/s11882-019-0878-4', true, '{5}', '{"MCAS","consensus","diagnosis","mast cell"}'),
(1, 'Gut Microbiome in ME/CFS: Systematic Review', 'microbiome-mecfs-2022', 'Systematic review of gut microbiome alterations in ME/CFS patients. Consistent findings of reduced diversity and specific bacterial depletions.', 'Gut microbiome alterations in ME/CFS', 1, 'https://doi.org/10.1186/s40168-022-01197-x', true, '{1,9}', '{"microbiome","systematic review","gut health","ME/CFS"}'),
(1, 'COVID-19 Vaccination and New-Onset POTS', 'covid-vaccine-pots-2024', 'Study examining cases of new-onset POTS following COVID-19 vaccination. Discusses mechanisms including autoantibody production and autonomic dysregulation.', 'New-onset POTS following COVID-19 vaccination', 2, 'https://doi.org/10.1016/j.hrthm.2023.12.001', true, '{2,3}', '{"POTS","COVID-19","vaccine","autonomic"}'),
(1, 'Stellate Ganglion Block for Long COVID', 'stellate-ganglion-block-2023', 'Case series and open-label study of stellate ganglion block for treating Long COVID symptoms including anosmia, dysautonomia, and brain fog.', 'Stellate ganglion block for Long COVID', 3, 'https://doi.org/10.3390/jcm12124025', true, '{2}', '{"stellate ganglion block","dysautonomia","treatment","case series"}'),
(1, 'Hyperbaric Oxygen Therapy for Long COVID', 'hbot-long-covid-2024', 'Randomised controlled trial of hyperbaric oxygen therapy for cognitive symptoms in Long COVID patients.', 'RCT of HBOT for Long COVID cognitive symptoms', 1, 'https://doi.org/10.1186/s10067-024-07001-3', true, '{2}', '{"hyperbaric","HBOT","cognitive","RCT"}'),
(1, 'IVIG for ME/CFS: Norwegian RCT', 'ivig-mecfs-2019', 'Randomised controlled trial of intravenous immunoglobulin (IVIG) for ME/CFS. Significant improvements in subgroups.', 'IVIG RCT for ME/CFS', 1, 'https://doi.org/10.1177/1359105319893026', true, '{1}', '{"IVIG","immunoglobulin","RCT","immune therapy"}'),
(8, 'McKinsey: The Future of Healthcare AI', 'mckinsey-healthcare-ai-2026', 'McKinsey analysis on health systems needing impact from AI, not more pilots. Framework for scaling AI-driven clinical improvements.', 'McKinsey on AI in healthcare - June 2026', 1, 'https://www.mckinsey.com/healthcare-ai-2026', true, '{9}', '{"McKinsey","AI","healthcare","strategy"}');

-- === CLINICS AND PROVIDERS ===
insert into public.listings (content_type_id, title, slug, description, summary, evidence_tier_id, website, city, state, country, listing_tier, is_published, categories) values
(4, 'Gold Coast University Hospital - Long COVID Clinic', 'gcu-long-covid-clinic', 'Specialist Long COVID clinic at Gold Coast University Hospital offering multidisciplinary assessment and management for post-COVID conditions.', 'Public hospital Long COVID clinic - Gold Coast', 5, 'https://www.goldcoast.health.qld.gov.au', 'Gold Coast', 'QLD', 'Australia', 'free', true, '{2}'),
(4, 'ME/CFS Centre of Excellence - Brisbane', 'mecfs-brisbane', 'Specialised assessment and management clinic for Myalgic Encephalomyelitis / Chronic Fatigue Syndrome. Offers multidisciplinary care including medical, occupational therapy, and psychology.', 'ME/CFS specialist centre - Brisbane', 5, 'https://www.mecfscentre.com.au', 'Brisbane', 'QLD', 'Australia', 'free', true, '{1}'),
(4, 'Sydney Heart Health - POTS Clinic', 'sydney-pots-clinic', 'Cardiology practice specialising in Postural Orthostatic Tachycardia Syndrome (POTS) and other autonomic disorders. Offers tilt-table testing and comprehensive management.', 'Specialist POTS clinic - Sydney', 5, 'https://www.sydneyhearthealth.com.au', 'Sydney', 'NSW', 'Australia', 'free', true, '{3}'),
(4, 'Fibromyalgia and Pain Management Centre', 'fibro-pain-centre', 'Multidisciplinary pain management centre specialising in fibromyalgia and chronic pain conditions. Combines medical management, physiotherapy, and psychological support.', 'Fibromyalgia pain management - Melbourne', 5, 'https://www.fibropaincentre.com.au', 'Melbourne', 'VIC', 'Australia', 'free', true, '{4}'),
(4, 'Autoimmune Wellness Clinic', 'autoimmune-wellness', 'Comprehensive clinic for autoimmune conditions offering integrated care combining rheumatology, immunology, nutrition, and lifestyle medicine.', 'Autoimmune integrated care - Adelaide', 5, 'https://www.autoimmunewellness.com.au', 'Adelaide', 'SA', 'Australia', 'free', true, '{7}'),
(5, 'Dr Sarah Mitchell - Immunologist', 'sarah-mitchell', 'Clinical immunologist specialising in MCAS, autoimmune conditions, and immunodeficiency disorders. Private practice with telehealth available.', 'Clinical immunologist - MCAS and autoimmune', 5, 'https://www.drmitchellimmunology.com', 'Perth', 'WA', 'Australia', 'free', true, '{5,7}'),
(5, 'Dr James Chen - Cardiologist (POTS)', 'james-chen-cardiologist', 'Cardiologist with subspecialty interest in autonomic disorders including POTS, syncope, and inappropriate sinus tachycardia. Public and private practice.', 'Cardiologist - POTS and autonomic disorders', 5, 'https://www.drchencardiology.com', 'Sydney', 'NSW', 'Australia', 'free', true, '{3}'),
(5, 'Dr Lisa Nguyen - Rheumatologist', 'lisa-nguyen-rheum', 'Rheumatologist with expertise in fibromyalgia, EDS/HSD, and autoimmune connective tissue diseases. Takes a holistic approach to chronic pain management.', 'Rheumatologist - fibromyalgia and EDS', 5, 'https://www.drnguyenrheum.com', 'Brisbane', 'QLD', 'Australia', 'free', true, '{4,6,7}'),
(5, 'Dr Emma Walsh - GP (Chronic Illness Focus)', 'emma-walsh-gp', 'General practitioner with special interest in chronic complex illness including ME/CFS, Long COVID, and POTS. Offers longer consultations and coordinated care.', 'GP specialising in chronic complex illness', 5, 'https://www.drwalshgp.com', 'Byron Bay', 'NSW', 'Australia', 'free', true, '{1,2,3}'),
(6, 'Long COVID Support Group - Northern Rivers', 'long-covid-support-northern-rivers', 'Peer-led support group for people with Long COVID in the Northern Rivers region of NSW. Meets monthly, both in-person (Ballina) and online.', 'Peer support group for Long COVID', 5, '', 'Ballina', 'NSW', 'Australia', 'free', true, '{2}'),
(6, 'ME/CFS Australia Online Community', 'mecfs-australia-community', 'National online support community for people with ME/CFS and their carers. Resource library, forums, and peer support network.', 'National ME/CFS support community', 5, 'https://www.mecfsaustralia.org.au', '', '', 'Australia', 'free', true, '{1}');

-- === TREATMENT PROTOCOLS ===
insert into public.listings (content_type_id, title, slug, description, summary, evidence_tier_id, external_url, is_published, categories) values
(2, 'Graded Exercise Therapy for ME/CFS', 'get-protocol', 'Structured, supervised exercise program starting at very low intensity and gradually increasing. Controversial due to PACE trial criticisms and risk of post-exertional malaise.', 'Structured exercise protocol - caution with PEM', 1, 'https://www.nice.org.uk/guidance/ng206', true, '{1}'),
(2, 'Pacing Protocol for Chronic Fatigue', 'pacing-protocol', 'Energy management strategy that involves balancing activity with rest to avoid post-exertional relapse. Widely accepted as first-line management for ME/CFS.', 'Energy management strategy for ME/CFS', 2, '', true, '{1,2}'),
(2, 'CHOP POTS Exercise Protocol', 'chop-pots-protocol', 'The Childrens Hospital of Philadelphia (CHOP) recumbent exercise protocol adapted for POTS. Gradual reconditioning program starting with recumbent cardio.', 'Exercise protocol for POTS', 2, 'https://www.chop.edu/pots-exercise-protocol', true, '{3}'),
(2, 'Long COVID Rehabilitation Protocol (WHO)', 'long-covid-rehab-who', 'World Health Organization rehabilitation protocol for post-COVID conditions. Guides graded return to activity with symptom monitoring.', 'WHO rehabilitation guidance for Long COVID', 1, 'https://www.who.int/publications/long-covid-rehab', true, '{2}');

-- === AFFILIATE PROGRAMS ===
insert into public.listings (content_type_id, title, slug, description, summary, external_url, is_published, categories) values
(7, 'iHerb Affiliate Program', 'iherb-affiliate', 'Global supplement retailer affiliate program. 5-15% commission on sales. Wide range of evidence-rated supplements available.', 'Supplement retailer affiliate - global shipping', 'https://www.iherb.com', true, '{9}'),
(7, 'Amazon Associates', 'amazon-associates', 'Amazon affiliate program for supplement and health product sales. Standard rates apply.', 'Major affiliate program for health products', 'https://affiliate-program.amazon.com', true, '{9}');
